services:
  stt:
    platform: linux/amd64
  translation:
    platform: linux/amd64
  tts:
    platform: linux/amd64
  assistant:
    platform: linux/amd64
  suggestion:
    platform: linux/amd64
  embedding:
    platform: linux/amd64
